### PR TITLE
Do not use GaudiAlg

### PR DESCRIPTION
**Pull request by jmcarcell**
These are the changes needed not to use GaudiAlg, which will be removed (maybe soon) in Gaudi.

Changes proposed in this pull-request:

- Do not link to GaudiAlgLib
- Add the necessary changes to the algorithm, use `Gaudi::Algorithm`, make `execute()` const and add a `const EventContext&`
- Add mutable to some elements that are changed; add const to some functions so that they can be called inside `execute(const EventContext&) const`
- Change `GaudiTool` to `AlgTool`

### CODE REVIEW

**Comment by jmcarcell** [comment]
Locally (using the Key4hep nightlies) this builds for me, there doesn't seem to be any `ctest` tests so I can't run them but behavior should be unchanged.

**Comment by jmcarcell** [comment]
This is another one that would be nice to have merged for building @kjvbrt or @BrieucF (and the last in the batch) I believe.

**Comment by kjvbrt** [comment]
Hi @jmcarcell can you rebase on top of #39 ?

**Comment by jmcarcell** [comment]
Done

**Comment by kjvbrt** [comment]
Thank you :)

**Pull request merged**
